simple mod

diff --git a/sh/tomcat b/sh/tomcat
--- a/sh/tomcat
+++ b/sh/tomcat
@@ -1,70 +1,52 @@
+#!/bin/bash
+# description:  Start Stop Restart and Status for Tomcat 7
+# processname: tomcat7
+
+
 die () {
     echo >&2 "$@"
     exit 1
 }
 
-[ "$#" -eq 1 ] || die "1 argument required {qab | qaa | prod}, $# provided"
+[ "$#" -eq 1 ] || die "Required argument {start | stop | status | restart}, $# provided"
 
-env=$1
+#JAVA_HOME=/usr/java/jre1.7.0_21
+JAVA_HOME=/usr/lib/jvm/java-1.6.0/
+export JAVA_HOME
+PATH=$JAVA_HOME/bin:$PATH
+export PATH
+CATALINA_HOME=/usr/share/tomcat7
 
-echo "--STOPING TOMCAT"
-sudo service tomcat7 stop
+function status_tomcat() {
+	echo "checking tomcat7 status ..."
+	wget -o wgetresponse http://localhost:8080
+	grep 'response\|failed' wgetresponse
+	sudo rm -rf wgetresponse index.html*
+}
 
-if [ $? != 0 ]; then
- die "unable to stop tomcat"
-fi
+function start_tomcat () {
+	echo "starting tomcat7 ..."
+	sh $CATALINA_HOME/bin/startup.sh
+}
 
-sleep 5
+function stop_tomcat () {
+	echo "stopping tomcat7 ..."
+	sh $CATALINA_HOME/bin/shutdown.sh
+}
 
-echo "--BACKING UP rules_engine.war"
-backupdir=rules_engine_backups/`date +%Y%m%d`
-mkdir -p $backupdir
-sudo cp -r /var/lib/tomcat7/webapps/rules_engine $backupdir/
-if [ $? != 0 ]; then
- die "unable to backup existing rules_engine webapp"
-fi
-
-echo "--CLEANING UP"
-sudo rm -rf /var/lib/tomcat7/webapps/rules_engine*
-if [ $? != 0 ]; then
- die "unable to remove webapp files"
-fi
-
-sudo rm -rf /var/lib/tomcat7/work/Catalina/*
-if [ $? != 0 ]; then
- die "unable to remove work files"
-fi
-
-sudo rm -f /var/log/tomcat7/*
-if [ $? != 0 ]; then
- die "unable to remove logs"
-fi
-
-
-echo "--INSTALLING NEW WAR"
-sudo mkdir -p /var/lib/tomcat7/webapps/rules_engine
-if [ $? != 0 ]; then
- die "unable to create /var/lib/tomcat7/webapps/rules_engine"
-fi
-
-sudo unzip rules_engine-*.war -d /var/lib/tomcat7/webapps/rules_engine
-if [ $? != 0 ]; then
- die "unable to deploy extract rules_engine.war"
-fi
-
-sudo cp /var/lib/tomcat7/webapps/rules_engine/WEB-INF/classes/beans.$env.xml /var/lib/tomcat7/webapps/rules_engine/WEB-INF/classes/beans.xml
-if [ $? != 0 ]; then
- die "unable to setup beans.xml"
-fi
-
-sudo cp /var/lib/tomcat7/webapps/rules_engine/WEB-INF/classes/META-INF/persistence.$env.xml /var/lib/tomcat7/webapps/rules_engine/WEB-INF/classes/META-INF/persistence.xml
-if [ $? != 0 ]; then
- die "unable to setup persistence.xml"
-fi
-
-echo "--STARTING TOMCAT"
-sudo service tomcat7 start
-if [ $? != 0 ]; then
- die "unable to start tomcat"
-fi
-
+case $1 in
+start)
+	start_tomcat
+;; 
+stop)   
+	stop_tomcat
+;; 
+status)
+	status_tomcat
+;;
+restart)
+	stop_tomcat
+	start_tomcat
+;; 
+esac    
+exit 0
